apiVersion: v2
name: promxy
description: A Helm chart for Promxy, a Prometheus proxy that combines multiple Prometheis
type: application
version: 0.1.0
appVersion: "v0.0.93"
kubeVersion: ">= 1.25.0-0"
home: https://github.com/jacksontj/promxy
sources:
  - https://github.com/jacksontj/promxy
keywords:
  - prometheus
  - promxy
  - monitoring
  - federation
  - high-availability
maintainers: []
annotations:
  artifacthub.io/license: MIT
  artifacthub.io/links: |
    - name: Chart Source
      url: https://github.com/jacksontj/promxy/tree/master/deploy/k8s/helm-charts/promxy
    - name: Promxy
      url: https://github.com/jacksontj/promxy
