// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package promclient

import (
	json "encoding/json"

	promhttputil "github.com/jacksontj/promxy/promhttputil"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
	model "github.com/prometheus/common/model"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson82e91527DecodeGithubComJacksontjPromxyPromclient(in *jlexer.Lexer, out *SeriesResult) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "status":
			out.Status = promhttputil.Status(in.String())
		case "data":
			if in.IsNull() {
				in.Skip()
				out.Data = nil
			} else {
				in.Delim('[')
				if out.Data == nil {
					if !in.IsDelim(']') {
						out.Data = make([]model.LabelSet, 0, 8)
					} else {
						out.Data = []model.LabelSet{}
					}
				} else {
					out.Data = (out.Data)[:0]
				}
				for !in.IsDelim(']') {
					var v1 model.LabelSet
					if data := in.Raw(); in.Ok() {
						in.AddError((v1).UnmarshalJSON(data))
					}
					out.Data = append(out.Data, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "errorType":
			out.ErrorType = promhttputil.ErrorType(in.String())
		case "error":
			out.Error = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson82e91527EncodeGithubComJacksontjPromxyPromclient(out *jwriter.Writer, in SeriesResult) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"status\":")
	out.String(string(in.Status))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"data\":")
	if in.Data == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in.Data {
			if v2 > 0 {
				out.RawByte(',')
			}
			(v3).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
	if in.ErrorType != "" {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"errorType\":")
		out.String(string(in.ErrorType))
	}
	if in.Error != "" {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"error\":")
		out.String(string(in.Error))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SeriesResult) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson82e91527EncodeGithubComJacksontjPromxyPromclient(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SeriesResult) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson82e91527EncodeGithubComJacksontjPromxyPromclient(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SeriesResult) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson82e91527DecodeGithubComJacksontjPromxyPromclient(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SeriesResult) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson82e91527DecodeGithubComJacksontjPromxyPromclient(l, v)
}
