{{- if .Values.verticalAutoscaler.enabled -}}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ template "chart.fullname" . }}-vpa
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    {{- with .Values.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: {{ template "chart.fullname" . }}
  updatePolicy:
    updateMode: {{ .Values.verticalAutoscaler.updateMode | default "Off" | quote }}
  resourcePolicy:
    containerPolicies:
      {{- toYaml (.Values.verticalAutoscaler.containerPolicies | default list) | nindent 6 }}
{{- end -}}
